services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: {{ env.POSTGRES_USER }}
      POSTGRES_PASSWORD: {{ env.POSTGRES_PASSWORD }}
      POSTGRES_DB: {{ env.POSTGRES_DB }}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:alpine"
    restart: always
    networks:
      - backend

  app:
    image: {{ env.IMAGE }}
    restart: always
    command: >
      sh -c "
        python manage.py makemigrations --no-input &&
        python manage.py migrate --no-input &&
        gunicorn id.wsgi:application \
          --bind 0.0.0.0:8081 \
          --access-logfile - \
          --error-logfile - \
          --capture-output \
          --log-level info \
          --workers 2 \
          --timeout 120 \
          --reload
      "
    container_name: app
    ports:
      - "80:8081"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DJANGO_SETTINGS_MODULE: {{ env.DJANGO_SETTINGS_MODULE }}
      SECRET_KEY: {{ env.SECRET_KEY }}
      BASE_DOMAIN: {{ env.BASE_DOMAIN }}
      ALLOWED_HOSTS: {{ env.ALLOWED_HOSTS }}
      CSRF_TRUSTED_ORIGINS: {{ env.CSRF_TRUSTED_ORIGINS }}
      CORS_ALLOWED_ORIGIN_REGEXES: {{ env.CORS_ALLOWED_ORIGIN_REGEXES }}
      POSTGRES_USER: {{ env.POSTGRES_USER }}
      POSTGRES_PASSWORD: {{ env.POSTGRES_PASSWORD }}
      POSTGRES_DB: {{ env.POSTGRES_DB }}
      LOCKOUT_REDIS_URL: {{ env.LOCKOUT_REDIS_URL }}
      REDIS_URL: {{ env.REDIS_URL }}
      EMAIL_VERIFICATION_REDIS_URL: {{ env.EMAIL_VERIFICATION_REDIS_URL }}
      EMAIL_HOST_PASSWORD: {{ env.EMAIL_HOST_PASSWORD }}
      EMAIL_HOST_USER: {{ env.EMAIL_HOST_USER }}
      COMPOSE_PROJECT_NAME: {{ env.COMPOSE_PROJECT_NAME }}
      SMARTCAPTCHA_SERVER_KEY: {{ env.SMARTCAPTCHA_SERVER_KEY }}
      SMARTCAPTCHA_VERIFY_URL: {{ env.SMARTCAPTCHA_VERIFY_URL }}
      PORT: 8081
    networks:
      - backend

volumes:
  dbdata:
    name: id_dbdata

networks:
  backend:
    driver: bridge
